### ISSUE TITLE
Buggy match box - can't enter doors/portals easily, can't navigate around corners easily

### ISSUE THREAD

**Issue by dumblob** [francoisschwarzentruber/sea#1]
Hi, this is a really cool idea! Kudos!

I though I'd show it to some children around me so I've just tried the demo and I think the "collision detection of sprite boundaries" will need some more love (will become especially annoying in fights/battles once enemies get implemented).

See the screenshot below where the door still can't be entered despite visually one would say it's definitely possible.

![20211007_165710+0200-1680x1050+0+0-imlib2_grab](https://user-images.githubusercontent.com/2451044/136412151-50612651-4063-45d1-aebd-bbd65a6ace26.png)

On the second screenshot the character can't go to the right even though it seems it should be possible. This one is quite annoying because this situation happens quite often if you go down the path to the "wall" and then back up and at the corner try to go to the right. It always fails - probably due to the size of one step the character makes which adds up to a certain position which seems already ok to go to the right at the corner, but it doesn't work yet :cry:.

![20211007_170200+0200-1680x1050+0+0-imlib2_grab](https://user-images.githubusercontent.com/2451044/136412198-22ceefa0-82d4-4ddd-b9a4-74e21121df35.png)

Generally I think the matchbox should actually be at least few pixels smaller than sprite itself. Because the whole crux of these problems lies within the mismatch between visualization and the actual behavior.

**Comment by francoisschwarzentruber** [comment]
Thank you for your detailed issue! I agree with you. The matchbox should be a bit smaller. But also, I think the player should *smoothly slide* along the obstacles when the collision is small. What do you think?

**Comment by dumblob** [comment]
>But also, I think the player should smoothly slide along the obstacles when the collision is small. What do you think?

Probably yes - I didn't study it in the detail and I'm not the most experienced person in game development to make such straight judgements off the head :wink:.

**Comment by francoisschwarzentruber** [comment]
I modified the code so that the player slides among the obstacles. :) That is why I closed the issue.
